<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.1;net6.0;net8.0</TargetFrameworks>
    <Description>This package provides a client for the Labelary API for rendering ZPL data</Description>
    <Company>Binary Kits Pte. Ltd.</Company>
    <Version>1.1.0-preview</Version>
    <Authors>Binary Kits Pte. Ltd., Daniel Dreibrodt</Authors>
    <PackageReleaseNotes>v1.1.0:
- Update dependencies</PackageReleaseNotes>
    <PackageTags>Zebra ZPL ZPL2 ZPLEmulator ZPLVirtualPrinter ZPLViewer Labelary</PackageTags>
    <PackageProjectUrl>https://github.com/3breadt/BinaryKits.Zpl</PackageProjectUrl>
    <RepositoryUrl>https://github.com/3breadt/BinaryKits.Zpl</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageIcon>logo_128.png</PackageIcon>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <AssemblyName>BinaryKits.Zpl.Labelary</AssemblyName>
    <RootNamespace>BinaryKits.Zpl.Labelary</RootNamespace>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
	<NoWarn>CS1591</NoWarn>
	<PackageId>3breadt.BinaryKits.Zpl.Labelary</PackageId>
	<PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="System.Net.Http" Version="4.*" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.1'">
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="6.*" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net6.0'">
	  <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="6.*" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.*" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\LICENSE" Pack="true" PackagePath="LICENSE" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\doc\logo_128.png">
      <Pack>true</Pack>
      <Visible>false</Visible>
      <PackagePath></PackagePath>
    </None>
    <None Include="..\..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
