<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net6.0;net8.0</TargetFrameworks>
    <Description>This package contains the zebra protocol of the Zebra Programming Language. It also supports you with image conversion.</Description>
    <Company>Binary Kits Pte. Ltd.</Company>
    <Version>1.1.0-preview</Version>
    <Authors>Binary Kits Pte. Ltd.</Authors>
    <PackageReleaseNotes>v1.1.0
- Removed .NET 4.7 support
- Upgraded SixLabors.ImageSharp to v3.1.10</PackageReleaseNotes>
    <PackageTags>Zebra ZPL ZPL2 Printer Protocol</PackageTags>
    <PackageProjectUrl>https://github.com/3breadt/BinaryKits.Zpl</PackageProjectUrl>
    <RepositoryUrl>https://github.com/3breadt/BinaryKits.Zpl</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageId>DD.BinaryKits.Zpl.Protocol</PackageId>
    <PackageIcon>logo_128.png</PackageIcon>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <AssemblyName>BinaryKits.Zpl.Protocol</AssemblyName>
    <RootNamespace>BinaryKits.Zpl.Protocol</RootNamespace>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
	<NoWarn>CS1591</NoWarn>
	<PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SixLabors.ImageSharp">
      <Version>3.1.10</Version>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\LICENSE" Pack="true" PackagePath="LICENSE" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\doc\logo_128.png">
      <Pack>true</Pack>
      <Visible>false</Visible>
      <PackagePath></PackagePath>
    </None>
    <None Include="..\..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
